name: Reproduce and Upload Artifacts

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        if [ -f "requirements.txt" ]; then
          pip install -r requirements.txt
        fi

    - name: Run analysis script
      run: |
        if [ -f "main.py" ]; then
          python main.py
        fi

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: demo-artifacts
        path: |
          R_plot.png
          output/
